# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/tristan/bbb_workspace/imic_embedded_linux_226002/poky/meta \
  /home/tristan/bbb_workspace/imic_embedded_linux_226002/poky/meta-poky \
  /home/tristan/bbb_workspace/imic_embedded_linux_226002/poky/meta-yocto-bsp \
  /home/tristan/bbb_workspace/imic_embedded_linux_226002/meta-imic \
  "
