# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-imic"
BBFILE_PATTERN_meta-imic = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-imic = "6"

LAYERDEPENDS_meta-imic = "core"
LAYERSERIES_COMPAT_meta-imic = "kirkstone"
